### ISSUE TITLE
Files missing from getting exported in packages

### ISSUE THREAD

**Issue by marvin5300** [MuonPi/libmuonpi#4]
Build packages with cpack (removed shlibs due to other bug during packaging).
Installed all generated packages on system using apt.
At least 'global.h', 'http_tools.h', 'log.h', 'threadrunner.h' are not in /usr/include/muonpi/

**Comment by dtreffenstaedt** [comment]
Fixed in https://github.com/MuonPi/libmuonpi/commit/0ef69d7aa4b642949b8446eb2a459bd4b816e132
